# Generated by Django 4.0.4 on 2022-04-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otapackage',
            options={'ordering': ('date_added',)},
        ),
        migrations.AddField(
            model_name='otapackage',
            name='hash',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
